name: fafarunner
description: Enjoy smooth gameplay, stunning graphics, and endless fun.
publish_to: 'none'

version: 2.5.2+382

environment:
  sdk: ^3.8.0

workspace:
  # basic
  - modules/basic/app
  - modules/basic/l10n
  - modules/basic/logger
  - modules/basic/shared
  - modules/basic/theme
  - modules/basic/url_strategy

  # ui
  - modules/ui/game

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.4.4
  sentry_flutter: ^9.1.0
  sentry_logging: ^9.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  import_sorter: ^4.6.0
  mockingjay: ^2.0.0
  mocktail: ^1.0.4
  msix: ^3.16.9
  very_good_analysis: ^9.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
flutter:
  uses-material-design: true
#  assets:
#    - logo/

msix_config:
  display_name: FaFa Runner
  logo_path: logo\logo-512.png
  languages: en-us, zh-cn
  architecture: x64
  capabilities: "internetClient"
  install_certificate: false

  # msix_version: 1.0.0.0 # If not set, the value of `version` is used
  # With Your Own Certificate 
  certificate_path: CERTIFICATE_PATH_PLACEHOLDER
  certificate_password: CERTIFICATE_PASSWORD_PLACEHOLDER

  # For Publish To Windows Store
  identity_name: IDENTITY_NAME_PLACEHOLDER
  publisher: PUBLISHER_PLACEHOLDER
  publisher_display_name: PUBLISHER_NAME_PLACEHOLDER

import_sorter:
  ignored_files: # Optional, defaults to []
    - \/lib\/gen\/*
    - \/lib\/i18n\/*
