name: fafarunner
description: Enjoy smooth gameplay, stunning graphics, and endless fun.
publish_to: 'none'

version: 3.2.1+396

environment:
  sdk: '>=3.12.0 <4.0.0'

workspace:
  # basic
  - modules/basic/app
  - modules/basic/l10n
  - modules/basic/logger
  - modules/basic/shared
  - modules/basic/theme
  - modules/basic/url_strategy

  # ui
  - modules/ui/game

dependencies:
  app: any
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.4.8
  game: any
  l10n: any
  logger: any
  sentry_flutter: ^9.25.0
  sentry_logging: ^9.25.0
  shared: any
  theme: any
  url_strategy: any

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.5

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
flutter:
  uses-material-design: true
#  assets:
#    - logo/
