name: fafarunner
summary: FaFa Runner
description: FaFa Runner
confinement: strict
base: core18
grade: stable
architectures:
  - build-on: [ amd64 ]
  - build-on: [ arm64 ]

apps:
  fafarunner:
    command: fafarunner
    extensions: [flutter-stable]
    plugs:
      - network

parts:
  fafarunner:
    source: .
    plugin: flutter
    flutter-target: lib/main.dart # The main entry-point file of the application
