display_name: FaFa Runner
icon: logo/logo-512.png
summary: FaFa Runner.
description: |
  Step into the enchanting world of FaFa Runner: Dawn Legends, where an epic adventure awaits! Developed using Flutter and the Flame engine, this RPG delivers a seamless gaming experience with stunning visual effects.
  
  Embark on your journey as a brave adventurer, explore mysterious lands, uncover hidden secrets, and face endless challenges. With rich story-driven quests and diverse character progression systems, every battle offers a unique sense of achievement.

  Key Features:
  1. Dynamic Combat System: Enjoy intuitive controls and fluid action as you take on powerful enemies and formidable bosses.
  2. Gorgeous Visuals: Experience vivid graphics and captivating animations, thanks to the powerful Flutter and Flame engine.
  3. Rich Quest System: Engage in main quests and side stories, with each adventure offering surprises and challenges.
  4. Customizable Character Growth: Tailor your hero with various skills and equipment to build the ultimate warrior.
  5. Interactive World Exploration: Discover hidden treasures and secret locations across a fantastical map.
  
  Join FaFa Runner: Dawn Legends and create your own legendary tale in this magical world. Download now and begin your epic adventure!
vendor: kjxbyz
packager: kjxbyz
packagerEmail: support@fafarunner.com
license: MIT
url: https://github.com/fafarunner/fafarunner
build_arch: x86_64

metainfo: linux/shared/fafarunner.metainfo.xml

keywords:
  - FaFa Runner

generic_name: FaFa Runner

# https://specifications.freedesktop.org/desktop-entry-spec/desktop-entry-spec-latest.html#introduction
# https://specifications.freedesktop.org/menu-spec/latest/apa.html
categories:
  - Game

# direct dependencies required by the application
# https://docs.redhat.com/zh-cn/documentation/red_hat_enterprise_linux/8/html/packaging_and_distributing_software/working-with-spec-files_packaging-software
requires:
  - libayatana-appindicator3-1

startup_notify: true
