display_name: FaFa Runner
icon: logo/logo-512.png
summary: FaFa Runner.
group: Application/Emulator
vendor: kjxbyz
packager: kjxbyz
packagerEmail: kjxbyz888@outlook.com
license: MIT
url: https://github.com/fafarunner/fafarunner
build_arch: x86_64

metainfo: linux/shared/fafarunner.metainfo.xml

keywords:
  - FaFa Runner

generic_name: FaFa Runner

# https://specifications.freedesktop.org/desktop-entry-spec/desktop-entry-spec-latest.html#introduction
# https://specifications.freedesktop.org/menu-spec/latest/apa.html
categories:
  - Game

startup_notify: true
