display_name: FaFa Runner
icon: logo/logo-512.png
summary: FaFa Runner.
description: Enjoy smooth gameplay, stunning graphics, and endless fun.
vendor: kjxbyz
packager: kjxbyz
packagerEmail: support@fafarunner.com
license: MIT
url: https://github.com/fafarunner/fafarunner
build_arch: x86_64

metainfo: linux/shared/fafarunner.metainfo.xml

keywords:
  - FaFa Runner
  - Tactical
  - RPG

generic_name: Tactical RPG Game

# https://specifications.freedesktop.org/desktop-entry-spec/desktop-entry-spec-latest.html#introduction
# https://specifications.freedesktop.org/menu-spec/latest/apa.html
categories:
  - Game

# direct dependencies required by the application
# https://docs.redhat.com/zh-cn/documentation/red_hat_enterprise_linux/8/html/packaging_and_distributing_software/working-with-spec-files_packaging-software
requires:
  - libayatana-appindicator3-1

startup_notify: true
