name: theme
description: theme module.
publish_to: none

environment:
  sdk: ^3.6.0
  flutter: '>=3.27.3'

resolution: workspace

# Add regular dependencies here.
dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  test: ^1.24.0
  very_good_analysis: ^7.0.0
