name: theme
description: theme module.
publish_to: none

environment:
  sdk: '>=3.9.0 <4.0.0'

resolution: workspace

# Add regular dependencies here.
dependencies:
  flutter:
    sdk: flutter
  flutter_gen: ^5.10.0

dev_dependencies:
  build_runner: ^2.5.4
  flutter_gen_runner: ^5.10.0
  flutter_test:
    sdk: flutter
  very_good_analysis: ^9.0.0
