name: theme
description: theme module.
publish_to: none

environment:
  sdk: ^3.7.0

resolution: workspace

# Add regular dependencies here.
dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^7.0.0
