display_name: FaFa Runner

icon: logo/logo512.png

keywords:
  - FaFa Runner

generic_name: FaFa Runner

#actions:
#  - name: Say Hi
#    label: say-hi
#    arguments:
#      - --say
#      - hi
#  - name: Say Bye
#    label: say-bye
#    arguments:
#      - --say
#      - bye

# https://specifications.freedesktop.org/desktop-entry-spec/desktop-entry-spec-latest.html#introduction
# https://specifications.freedesktop.org/menu-spec/latest/apa.html
categories:
  - Game

startup_notify: true

# You can specify the shared libraries that you want to bundle with your app
#
# flutter_distributor automatically detects the shared libraries that your app
# depends on, but you can also specify them manually here.
#
# The following example shows how to bundle the libcurl library with your app.
#
# include:
#   - libcurl.so.4
include: []
