targets:
  $default:
    builders:
      slang_build_runner:
        options:
          base_locale: en
          fallback_strategy: base_locale
          input_directory: assets/i18n
          output_directory: lib/src
          output_file_name: l10n.g.dart
          maps:
            - locales
