display_name: FaFa Runner
package_name: fafarunner
maintainer:
  name: kjxbyz
  email: hello@kjxbyz.com
priority: optional
section: x11
installed_size: 24400
essential: false
icon: logo/logo-512.png
metainfo: linux/shared/fafarunner.metainfo.xml

keywords:
  - FaFa Runner

generic_name: FaFa Runner

# https://specifications.freedesktop.org/desktop-entry-spec/desktop-entry-spec-latest.html#introduction
# https://specifications.freedesktop.org/menu-spec/latest/apa.html
categories:
  - Game

startup_notify: true
