name: fafarunner
version: 2.5.2.382
summary: Enjoy smooth gameplay, stunning graphics, and endless fun.
description: |
  Step into the enchanting world of FaFa Runner: Dawn Legends, where an epic adventure awaits! Developed using Flutter and the Flame engine, this RPG delivers a seamless gaming experience with stunning visual effects.
  
  Embark on your journey as a brave adventurer, explore mysterious lands, uncover hidden secrets, and face endless challenges. With rich story-driven quests and diverse character progression systems, every battle offers a unique sense of achievement.

  Key Features:
  1. Dynamic Combat System: Enjoy intuitive controls and fluid action as you take on powerful enemies and formidable bosses.
  2. Gorgeous Visuals: Experience vivid graphics and captivating animations, thanks to the powerful Flutter and Flame engine.
  3. Rich Quest System: Engage in main quests and side stories, with each adventure offering surprises and challenges.
  4. Customizable Character Growth: Tailor your hero with various skills and equipment to build the ultimate warrior.
  5. Interactive World Exploration: Discover hidden treasures and secret locations across a fantastical map.
  
  Join FaFa Runner: Dawn Legends and create your own legendary tale in this magical world. Download now and begin your epic adventure!
icon: snap/gui/fafarunner.png
title: FaFa Runner
contact: hello@kjxbyz.com
license: MIT
source-code: https://github.com/fafarunner/fafarunner
issues: https://github.com/fafarunner/fafarunner/issues
website: https://www.fafarunner.com
confinement: strict
base: core22
grade: stable
slots:
  dbus-fafarunner: # adjust accordingly to your app name
    interface: dbus
    bus: session
    name: com.fafarunner.FaFaRunner # adjust accordingly to your app name and
apps:
  fafarunner:
    command: fafarunner
    extensions: [gnome] # gnome includes the libraries required by flutter
    plugs:
      - network
    slots:
      - dbus-fafarunner
parts:
  fafarunner:
    source: .
    plugin: flutter
    # flutter-target: lib/main.dart # The main entry-point file of the application
    build-environment:
      - FLUTTER_REPO: https://github.com/flutter/flutter.git
      - FLUTTER_VERSION: 3.32.5
      - FLUTTER_TARGET: lib/main.dart
    build-packages:
      - curl
      - libcurl4-openssl-dev # https://github.com/actions/runner-images/issues/6399#issuecomment-1285011525
      - git
      - unzip
      - xz-utils
      - zip
      - libglu1-mesa
      - clang
      - cmake
      - ninja-build
      - pkg-config
      - libgtk-3-dev
      - liblzma-dev
      - libstdc++-12-dev
      - libunwind-dev
      - libgstreamer1.0-dev
      - libgstreamer-plugins-base1.0-dev
      - libayatana-appindicator3-dev # used by tray_manager
    stage-packages:
      - libayatana-appindicator3-1
    override-build: |
      apt update
      apt install -y openjdk-21-jdk
      
      arch=$(uname -m)
      if [[ "$arch" == "aarch64" ]]; then
        export JAVA_HOME=/usr/lib/jvm/java-21-openjdk-arm64
      elif [[ "$arch" == "x86_64" ]]; then
        export JAVA_HOME=/usr/lib/jvm/java-21-openjdk-amd64
      else
        echo "Unknown arch"
      fi
      
      export PATH="$PATH":"$HOME/.pub-cache/bin":":$JAVA_HOME/bin"

      java -version
      
      # https://github.com/canonical/snapcraft/blob/main/snapcraft/parts/plugins/flutter_plugin.py
      FR_FLUTTER_BUILD_DIR="$CRAFT_PART_BUILD/flutter-distro"
      if [ -d "$FR_FLUTTER_BUILD_DIR" ]; then
        echo "$FR_FLUTTER_BUILD_DIR"
        rm -rf $FR_FLUTTER_BUILD_DIR
      fi
      git clone --depth 1 -b $FLUTTER_VERSION $FLUTTER_REPO $FR_FLUTTER_BUILD_DIR
      
      # https://github.com/canonical/snapcraft/pull/5264
      # Fixed in 3.29.1
      # rm -f "$FR_FLUTTER_BUILD_DIR/engine/src/.gn"
      flutter doctor -v
      flutter precache --linux
      flutter pub get
      
      export SENTRY_NATIVE_BACKEND=breakpad
      flutter build linux --release --dart-define-from-file=.env --target $FLUTTER_TARGET
      cp -r build/linux/*/release/bundle/* $CRAFT_PART_INSTALL/
