targets:
  $default:
    builders:
      flutter_gen_runner:
        options:
          output: lib/gen/ # Optional (default: lib/gen/)
          line_length: 80 # Optional (default: 80)
          assets:
            outputs:
              package_parameter_enabled: true
          fonts:
            outputs:
              package_parameter_enabled: true
