on:
  pull_request:
    branches: [ "main" ]
name: Build and Release Web
jobs:
  build:
    name: Build Web
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          flutter-version: '3.13.0'

      - name: Flutter doctor -v
        run: flutter doctor -v

      - name: Install Deps
        run: flutter pub get

      - name: Build Web
        run: flutter build web --no-tree-shake-icons --web-renderer canvaskit --base-href /fafa-runner/play/
