name: Release web
run-name: Release web ${{ github.ref_name }}

on:
  # Enable manual run
  workflow_dispatch:

# Declare default permissions as readonly.
permissions: read-all

jobs:
  web:
    name: Create web
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v5

      - name: Install dependencies for Linux
        run: |
          # https://github.com/getsentry/sentry-dart/issues/2504
          sudo apt-get update -y && sudo apt-get upgrade -y
          sudo apt-get install -y curl libcurl4-openssl-dev git unzip xz-utils zip libglu1-mesa
          sudo apt-get install -y clang cmake ninja-build pkg-config libgtk-3-dev liblzma-dev libstdc++-12-dev

      - name: Install GStreamer
        run: |
          # Install libunwind-dev, see https://github.com/actions/runner-images/issues/6399#issuecomment-1285011525
          sudo apt-get install -y libunwind-dev libgstreamer1.0-dev libgstreamer-plugins-base1.0-dev

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          flutter-version: '3.32.8'

      - name: Configure .env
        run: echo "$ENV_PROD_BASE64" | base64 --decode > .env
        env:
          ENV_PROD_BASE64: ${{ secrets.ENV_PROD_BASE64 }}

      - name: Flutter doctor -v
        run: flutter doctor -v

      - name: Install flutter dependencies
        run: flutter pub get

      - name: Build flutter
        run: flutter build web --dart-define-from-file=.env --base-href /play/

      - name: Copy files to flutter web
        run: cp LICENSE README.md ./build/web

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.FR_RELEASE_TOKEN }}
          publish_dir: ./build/web
          cname: fafarunner-web.fafarunner.com

      - name: Clean up
        if: ${{ always() }}
        run: rm -f .env
