name: Test Linux tar (arm64 deprecated)

on:
  workflow_dispatch:

# Declare default permissions as readonly.
permissions: read-all

jobs:
  tar:
    name: Create linux tar (aarch64)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: arm64

      - name: Configure .env
        run: |
          echo "$ENV_KEY" | base64 --decode > .env
        env:
          ENV_KEY: ${{ secrets.ENV_STG_BASE64 }}

      - name: Install qemu-user-static
        run: |
          docker run --rm --privileged multiarch/qemu-user-static --reset -p yes

      - uses: addnab/docker-run-action@v3
        with:
          image: arm64v8/ubuntu:22.04
          options: |
            --rm
            --cap-add SYS_ADMIN
            --device /dev/fuse
            --security-opt apparmor:unconfined
            -v ${{ github.workspace }}:/work
            --workdir /work
          shell: bash
          run: |
            set -x
            # Show linux info
            echo "Show linux info"
            uname --all

            # Install dependencies for Linux
            echo "Install dependencies for Linux"
            apt update && apt install -y sudo
            sudo apt install -y wget curl git unzip xz-utils zip libglu1-mesa file
            sudo apt install -y clang cmake ninja-build pkg-config libgtk-3-dev liblzma-dev
            sudo apt install -y p7zip-full p7zip-rar
            
            # Install libunwind-dev, see https://github.com/actions/runner-images/issues/6399#issuecomment-1285011525
            sudo apt install -y libunwind-dev
            sudo apt install -y libgstreamer1.0-dev libgstreamer-plugins-base1.0-dev

            # Setup Flutter
            echo "Setup Flutter"
            bash ./scripts/install-flutter-ubuntu.sh

            if [ -d "/home/linux-arm64/flutter" ]; then
              echo "🟩 ls -la"
              ls -la /home/linux-arm64/flutter
            fi
            echo 'export PATH="$PATH:/home/linux-arm64/flutter/bin:/home/linux-arm64/flutter/.pub-cache/bin:$HOME/.pub-cache/bin"' >> ~/.zshrc
            source ~/.zshrc
            echo $PATH

            # Flutter doctor
            echo "Flutter doctor -v"
            flutter doctor -v

            # Install flutter dependencies
            echo "Install flutter dependencies"
            flutter pub get
            
            # Build flutter
            echo "Build flutter"
            flutter build linux --dart-define-from-file=.env --target-platform=linux-arm64
            
            # Install yq
            if ! command -v yq >/dev/null 2>&1; then
              echo "yq not exists"
              wget https://github.com/mikefarah/yq/releases/latest/download/yq_linux_arm64 -O /usr/bin/yq &&\
              chmod +x /usr/bin/yq
            fi
            yq --version
            
            # Get version
            echo "Get version"
            version=$(yq '.version' pubspec.yaml)

            # Build tar
            echo "Build tar"
            baseDir=$(pwd)
            archiveName="fafarunner_"$version"_linux_aarch64.tar.gz"
            cd build/linux/arm64/release/bundle
            tar -czaf $archiveName ./*
            mv $archiveName "$baseDir/"

      # Package the build.
      - name: Copy build for tar
        run: ls -la *.tar.gz

      - uses: actions/upload-artifact@v4
        with:
          name: linux-tar-arm64-artifact
          path: |
            ./*.tar.gz

      - name: Clean up
        if: ${{ always() }}
        run: |
          rm -f .env
