name: Test Linux Flatpak

on:
  workflow_dispatch:

# Declare default permissions as readonly.
permissions: read-all

jobs:
  flatpak:
    name: Create linux flatpak
    runs-on: ubuntu-latest
    container:
      image: bilelmoussaoui/flatpak-github-actions:freedesktop-22.08
      options: --privileged
    steps:
      - uses: actions/checkout@v4

      - name: Install yq
        run: |
          if ! command -v yq >/dev/null 2>&1; then
            echo "yq not exists"
            if ! command -v wget >/dev/null 2>&1; then
              echo "wget not exists"
              sudo dnf -y install wget
            fi
            wget https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 -O /usr/bin/yq &&\
            chmod +x /usr/bin/yq
          fi
          yq --version

      - name: Set version
        id: version_step
        run: |
          VERSION=$(yq '.version' pubspec.yaml)
          echo "$VERSION"
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Build .flatpak
        uses: flatpak/flatpak-github-actions/flatpak-builder@master
        with:
          bundle: FaFaRunner_${{ steps.version_step.outputs.version }}_linux_x86_64.flatpak
          manifest-path: flatpak/com.chenyifaer.FaFaRunner.json
          cache: true
          restore-cache: true
          cache-key: flatpak-builder-${{ github.sha }}-cache-restored
          arch: x86_64
          upload-artifact: false

      # Package the build.
      - name: Copy build for flatpak
        run: |
          ls -la

      - uses: actions/upload-artifact@v4
        with:
          name: linux-flatpak-artifact
          path: |
            ./*.flatpak

      - name: Clean up
        if: ${{ always() }}
        run: |
          rm -f .env
