name: Test Linux AppImage

on:
  workflow_dispatch:

# Declare default permissions as readonly.
permissions: read-all

jobs:
  appimage:
    name: Create linux appimage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies for Linux
        run: |
          sudo apt-get update -y && sudo apt-get upgrade -y
          sudo apt-get install -y curl git unzip xz-utils zip libglu1-mesa
          sudo apt-get install -y clang cmake ninja-build pkg-config libgtk-3-dev liblzma-dev libstdc++-12-dev
          sudo apt-get install -y locate libfuse2
          wget -O appimagetool "https://github.com/AppImage/AppImageKit/releases/download/continuous/appimagetool-x86_64.AppImage"
          chmod +x appimagetool && mv appimagetool /usr/local/bin/

      - name: Install GStreamer
        run: |
          # Install libunwind-dev, see https://github.com/actions/runner-images/issues/6399#issuecomment-1285011525
          sudo apt-get install -y libunwind-dev libgstreamer1.0-dev libgstreamer-plugins-base1.0-dev

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          flutter-version: '3.24.5'

      - name: Flutter doctor -v
        run: flutter doctor -v

      - name: Configure .env
        run: |
          echo "$ENV_KEY" | base64 --decode > .env
        env:
          ENV_KEY: ${{ secrets.ENV_STG_BASE64 }}

      - name: Install flutter_distributor
        run: dart pub global activate flutter_distributor

      - name: Install flutter dependencies
        run: flutter pub get

      - name: Build AppImage
        run: |
          flutter_distributor package \
            --flutter-build-args "dart-define-from-file=.env,target-platform=linux-x64" \
            --platform linux \
            --targets appimage \
            --artifact-name '{{name}}_{{build_name}}+{{build_number}}_{{platform}}_amd64.{{ext}}'

      # Package the build.
      - name: Copy build for AppImage
        run: ls -laR
        working-directory: dist

      - uses: actions/upload-artifact@v4
        with:
          name: linux-appimage-artifact
          path: |
            ./dist/**/*.AppImage

      - name: Clean up
        if: ${{ always() }}
        run: |
          rm -f .env
