name: Test Git

on:
  workflow_dispatch:

# Declare default permissions as readonly.
permissions: read-all

jobs:
  git:
    name: Test git
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set commit_count
        id: commit_count_step
        run: |
          echo "Current ref name: $BRANCH"
          echo "commit_count=$(git rev-list --count $BRANCH)" >> $GITHUB_OUTPUT
        env:
          BRANCH: ${{ github.ref_name }}

      - name: Check commit_count
        run: echo ${{ steps.commit_count_step.outputs.commit_count }}
