name: Test Linux Snapcraft (arm64)

on:
  workflow_dispatch:

# Declare default permissions as readonly.
permissions: read-all

jobs:
  snap:
    name: Create linux snap (aarch64)
    runs-on: buildjet-4vcpu-ubuntu-2204-arm
    env:
      LXD_GROUP: lxd
    steps:
      - uses: actions/checkout@v4

      - name: Install yq
        run: |
          if ! command -v yq >/dev/null 2>&1; then
            echo "yq not exists"
            sudo snap install -y yq
          fi
          yq --version

      - name: Configure .env
        run: |
          echo "$ENV_KEY" | base64 --decode > .env
        env:
          ENV_KEY: ${{ secrets.ENV_STG_BASE64 }}

      - name: Setup LXD
        uses: canonical/setup-lxd@main
        with:
          group: ${{ env.LXD_GROUP }}
          channel: latest/stable

      - name: Add user to the LXD (lxd) group
        run: |
          sudo usermod -a -G $LXD_GROUP $USER
          newgrp $LXD_GROUP

      - name: Restart lxd
        run: sudo snap restart lxd

      - name: Update snapcraft.yaml
        run: |
          rm -f snap/snapcraft.yaml
          mv snap/snapcraft-arm64.yaml snap/snapcraft.yaml

      - name: Install snapcraft
        run: sudo snap install snapcraft --classic

      - name: Build snap
        run: |
          # https://snapcraft.io/docs/flutter-applications
          version=$(yq '.version' pubspec.yaml)
          sudo snapcraft --output "fafarunner_"$version"_linux_aarch64.snap"

      # Package the build.
      - name: Copy build for snap
        run: ls -la *.snap

      - uses: actions/upload-artifact@v4
        with:
          name: linux-snap-arm64-artifact
          path: |
            ./*.snap

      - name: Clean up
        if: ${{ always() }}
        run: |
          rm -f .env
          if which snapcraft >/dev/null 2>&1; then
            echo "snapcraft exists"
            sudo snapcraft clean
          fi