name: Test Linux Flatpak

on:
  workflow_dispatch:

# Declare default permissions as readonly.
permissions: read-all

jobs:
  flatpak:
    name: Create flatpak
    runs-on: ubuntu-latest
    container:
      image: bilelmoussaoui/flatpak-github-actions:freedesktop-23.08
      options: --privileged
    steps:
      - uses: actions/checkout@v4

      - name: Install yq
        run: |
          if ! command -v yq >/dev/null 2>&1; then
            echo "yq not exists"
            if ! command -v wget >/dev/null 2>&1; then
              echo "wget not exists"
              sudo dnf -y install wget
            fi
            wget https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 -O /usr/bin/yq &&\
            chmod +x /usr/bin/yq
          fi
          yq --version

      - name: Set version
        id: version_step
        run: |
          VERSION=$(yq '.version' pubspec.yaml)
          echo "$VERSION"

          VERSION_SHORT=$(echo "$VERSION" | sed -e "s/+.*//")
          echo "$VERSION_SHORT"

          BUILD_NUMBER=$(echo "$VERSION" | sed -e "s/.*+//")
          echo "$BUILD_NUMBER"

          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "version_short=$VERSION_SHORT" >> $GITHUB_OUTPUT
          echo "build_number=$BUILD_NUMBER" >> $GITHUB_OUTPUT

      - name: Update version
        run: |
          # Update flatpak/com.chenyifaer.FaFaRunner.yml
          TAG="$([[ "$ENV" == "staging" ]] && echo "$TAG_NAME.pre" || echo "$TAG_NAME")"
          RELEASE="$([[ "$ENV" == "staging" ]] && echo "$VERSION.pre" || echo "$VERSION")"

          url=https://github.com/fafarunner/fafarunner/releases/download/"$TAG"/fafarunner_"$RELEASE"_linux_amd64.deb
          wget -O fafarunner.deb "$url"
          sha256=$(sha256sum fafarunner.deb | awk '{print $1}')
          rm -f fafarunner.deb
          url=$url yq -i '.modules[0].sources[0].url = strenv(url)' flatpak/com.chenyifaer.FaFaRunner.yml
          sha256=$sha256 yq -i '.modules[0].sources[0].sha256 = strenv(sha256)' flatpak/com.chenyifaer.FaFaRunner.yml

          desktop_url=https://raw.githubusercontent.com/fafarunner/fafarunner/"$TAG"/linux/shared/com.chenyifaer.FaFaRunner.desktop
          wget -O com.chenyifaer.FaFaRunner.desktop "$desktop_url"
          desktop_sha256=$(sha256sum com.chenyifaer.FaFaRunner.desktop | awk '{print $1}')
          rm -f com.chenyifaer.FaFaRunner.desktop
          desktop_url=$desktop_url yq -i '.modules[0].sources[2].url = strenv(desktop_url)' flatpak/com.chenyifaer.FaFaRunner.yml
          desktop_sha256=$desktop_sha256 yq -i '.modules[0].sources[2].sha256 = strenv(desktop_sha256)' flatpak/com.chenyifaer.FaFaRunner.yml

          appdata_url=https://raw.githubusercontent.com/fafarunner/fafarunner/"$TAG"/linux/shared/com.chenyifaer.FaFaRunner.appdata.xml
          wget -O com.chenyifaer.FaFaRunner.appdata.xml "$appdata_url"
          appdata_sha256=$(sha256sum com.chenyifaer.FaFaRunner.appdata.xml | awk '{print $1}')
          rm -f com.chenyifaer.FaFaRunner.appdata.xml
          appdata_url=$appdata_url yq -i '.modules[0].sources[3].url = strenv(appdata_url)' flatpak/com.chenyifaer.FaFaRunner.yml
          appdata_sha256=$appdata_sha256 yq -i '.modules[0].sources[3].sha256 = strenv(appdata_sha256)' flatpak/com.chenyifaer.FaFaRunner.yml
        env:
          ENV: ${{ github.event.inputs.env }}
          TAG_NAME: "v${{ steps.version_step.outputs.version }}"
          VERSION: ${{ steps.version_step.outputs.version }}

      - name: Build .flatpak
        uses: flatpak/flatpak-github-actions/flatpak-builder@master
        with:
          bundle: FaFaRunner_${{ steps.version_step.outputs.version }}_linux_amd64.flatpak
          manifest-path: flatpak/com.chenyifaer.FaFaRunner.yml
          cache: true
          restore-cache: true
          cache-key: flatpak-builder-${{ github.sha }}-cache-restored
          arch: x86_64
          upload-artifact: false

      # Package the build.
      - name: Copy build for flatpak
        run: |
          ls -la

      - uses: actions/upload-artifact@v4
        with:
          name: linux-flatpak-artifact
          path: |
            ./*.flatpak

      - name: Clean up
        if: ${{ always() }}
        run: |
          rm -f .env
