name: Test Linux Pacman (arm64)

on:
  workflow_dispatch:

# Declare default permissions as readonly.
permissions: read-all

jobs:
  pacman:
    name: Create linux pacman (aarch64)
    runs-on: buildjet-4vcpu-ubuntu-2204-arm
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies for Linux
        run: |
          sudo apt update
          sudo apt install -y wget curl git unzip xz-utils zip libglu1-mesa file
          sudo apt install -y clang cmake ninja-build pkg-config libgtk-3-dev liblzma-dev
          sudo apt install -y locate libfuse2
          sudo apt install -y libarchive-tools

      - name: Install libunwind-dev
        run: |
          # https://github.com/actions/runner-images/issues/6399#issuecomment-1285011525
          sudo apt install -y libunwind-dev
          sudo apt install -y libgstreamer1.0-dev libgstreamer-plugins-base1.0-dev

      - name: Setup Flutter
        shell: bash
        run: |
          chmod +x ./scripts/install-flutter-ubuntu-actions.sh
          ./scripts/install-flutter-ubuntu-actions.sh

      - name: Flutter doctor -v
        run: flutter doctor -v

      - name: Configure .env
        run: |
          echo "$ENV_KEY" | base64 --decode > .env
        env:
          ENV_KEY: ${{ secrets.ENV_STG_BASE64 }}

      - name: Install flutter_distributor
        run: |
          dart pub global activate \
            --source git https://github.com/kjxbyz/flutter_distributor \
            --git-ref pacman \
            --git-path packages/flutter_distributor
  
      - name: Install flutter dependencies
        run: flutter pub get

      - name: Build Pacman
        run: |
          flutter_distributor package \
            --flutter-build-args "dart-define-from-file=.env,target-platform=linux-arm64" \
            --platform linux \
            --targets pacman \
            --artifact-name '{{name}}_{{build_name}}+{{build_number}}_{{platform}}_aarch64.{{ext}}'

      # Package the build.
      - name: Copy build for Pacman
        run: ls -laR
        working-directory: dist

      - uses: actions/upload-artifact@v4
        with:
          name: linux-pacman-arm64-artifact
          path: |
            ./dist/**/*.pacman

      - name: Clean up
        if: ${{ always() }}
        run: |
          rm -f .env
