name: Test Web

on:
  workflow_dispatch:

# Declare default permissions as readonly.
permissions: read-all

jobs:
  web:
    name: Create web
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies for Linux
        run: |
          # https://github.com/getsentry/sentry-dart/issues/2504
          sudo apt-get update -y && sudo apt-get upgrade -y
          sudo apt-get install -y curl libcurl4-openssl-dev git unzip xz-utils zip libglu1-mesa
          sudo apt-get install -y clang cmake ninja-build pkg-config libgtk-3-dev liblzma-dev libstdc++-12-dev

      - name: Install GStreamer
        run: |
          # Install libunwind-dev, see https://github.com/actions/runner-images/issues/6399#issuecomment-1285011525
          sudo apt-get install -y libunwind-dev libgstreamer1.0-dev libgstreamer-plugins-base1.0-dev

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          flutter-version: '3.32.0'

      - name: Configure .env
        run: echo "$ENV_STG_BASE64" | base64 --decode > .env
        env:
          ENV_STG_BASE64: ${{ secrets.ENV_STG_BASE64 }}

      - name: Flutter doctor -v
        run: flutter doctor -v

      - name: Install flutter dependencies
        run: flutter pub get

      - name: Build flutter
        run: flutter build web --dart-define-from-file=.env

      - uses: actions/upload-artifact@v4
        with:
          name: web-artifact
          path: ./build/web

      - name: Clean up
        if: ${{ always() }}
        run: |
          rm -f .env
